"""Shared constants for the vulnerability analyzer."""

STATUS_YES = "ДА"
STATUS_NO = "НЕТ"
STATUS_LINUX = "ЛИНУКС"
STATUS_CONDITIONAL = "УСЛОВНО"
STATUS_REPEAT = "ПОВТОР"
STATUS_EMPTY = ""

ALL_STATUSES = (STATUS_YES, STATUS_NO, STATUS_LINUX, STATUS_CONDITIONAL, STATUS_REPEAT)

SOURCE_JOURNAL = "journal"
SOURCE_KNOWLEDGE_BASE = "knowledge_base"
SOURCE_AUTO_NO_MATCH = "auto_no_match"
SOURCE_MANUAL = "manual"

MATCH_EXACT = "exact"
MATCH_CONTAINS = "contains"
MATCH_REGEX = "regex"
MATCH_VECTOR = "vector"

ALL_MATCH_TYPES = (MATCH_EXACT, MATCH_CONTAINS, MATCH_REGEX, MATCH_VECTOR)

SOURCE_LOCAL_PPTS = "local_ppts"
SOURCE_GENERAL_PPTS = "general_ppts"

DEFAULT_TOP_N = 10
DEFAULT_VECTOR_THRESHOLD = 0.5
DEFAULT_FUZZY_THRESHOLD = 75
DEFAULT_TRANSLITERATION_DIRECTION = "to_en"
DEFAULT_MIN_WORD_LENGTH = 3

DB_DEFAULT_FILENAME = "knowledge.db"

EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
EMBEDDING_MODEL_MULTILINGUAL = "paraphrase-multilingual-MiniLM-L12-v2"
